version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "food2vec"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uvbxmnx3x6vt"
s3_prefix = "food2vec"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

